version: "3"
services:
  web:
    image: nginx
    volumes:
      - ./web/build:/var/www
      - ./web/build:/usr/share/nginx/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/bash -c "rm -rf /usr/share/nginx/html/* && exec nginx -g 'daemon off;'"
    depends_on:
      - flask
  flask:
    restart: always
    image: "flask_api"
    build: ./coreService/
    ports:
      - "5000:5000"
    container_name: "flask_api"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    user: "${UID}:${GID}"
    volumes:
      - ./coreService/data/db/:/data/db/
    ports:
      - "27017:27017"
