version: "3"
services:
  
  web:
    image: web_ui
    build: ./web/
    container_name: "web_ui"
    ports:
      - "8080:80"
    depends_on:
      - flask
  
  flask:
    restart: always
    image: "flask_api"
    build: ./coreService/
    ports:
      - "5000:5000"
    container_name: "flask_api"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mongo
  
  mongo:
    image: "mongo"
    user: "${MONGO_UID}:${MONGO_GID}"
    container_name: "mongodb_container"
    volumes:
      - ${MONGO_DATA_PATH}:/data/db/
    ports:
      - "27017:27017"
  
  translator:
    image: "translator"
    build: ./translator  
    environment:
      - API_KEY=${TRANSLATOR_API_KEY}
      - API_ADDRESS=http://flask:5000/api/wiki
    container_name: "translator"
    depends_on:
      - flask
  
  tg_userbot:
    # restart: always
    image: "searchbot"
    environment:
      - API_HOST=flask
      - API_PORT=5000
      - USER_BOT_TOKEN = ${TG_USERBOT_TOKEN}
      - PROXY_URL = ${PROXY_URL}
      - PROXY_LOGIN = ${PROXY_LOGIN}
      - PROXY_PASSWORD = ${PROXY_PASSWORD}
    build: ./telegramBots/userBot/
    container_name: "search_bot"
    depends_on:
      - flask
  
  tg_editbot:
    image: "editorbot"
    environment:
      - API_HOST=flask
      - API_PORT=5000
      - USER_BOT_TOKEN = ${TG_EDITORBOT_TOKEN}
      - PROXY_URL = ${PROXY_URL}
      - PROXY_LOGIN = ${PROXY_LOGIN}
      - PROXY_PASSWORD = ${PROXY_PASSWORD}
    build: ./telegramBots/editBot/
    container_name: "editor_bot"
    depends_on:
      - flask
