version: "3"
services:
  flask:
    restart: always
    image: "flask_api"
    build: ./coreService/
    ports:
      - "5000:5000"
    container_name: "flask_api"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    volumes:
      - ./data/db/:/data/db/
    ports:
      - "27017:27017"
  web:
    image: "web"
    build: ./web/
    ports:
      - "8000:8000"
    container_name: "web"
    volumes:
      - ./web:/usr/src/app
