version: "3"
services:
  web:
    image: nginx
    volumes:
      - ./web:/var/www
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: >
      /bin/bash -c "rm -rf /usr/share/nginx/html/* && 
      apt-get update &&
      apt-get install npm -y &&
      cd /var/www &&
      npm install &&
      npm install react-scripts &&
      npm run build &&
      cp -R /var/www/build/* /usr/share/nginx/html &&
      exec nginx -g 'daemon off;'"
    depends_on:
      - flask
  flask:
    restart: always
    image: "flask_api"
    build: ./coreService/
    ports:
      - "5000:5000"
    container_name: "flask_api"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    user: "${UID}:${GID}"
    container_name: "mongodb_container"
    volumes:
      - ./coreService/data/db/:/data/db/
    ports:
      - "27017:27017"
  translator:
    image: "translator"
    build: ./translator
    container_name: "translator"
    depends_on:
      - flask
  TG_userBot:
    restart: always
    image: "userBot"
    build: ./telegramBots/userBot/
    container_name: "userBot"
