version: "3"
services:
  flask:
    restart: always
    image: "flask_api"
    build: ./coreService
    ports:
      - "5000:5000"
    container_name: "flask_api"
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    user: "${UID}:${GID}"
    volumes:
      - ./data/db/:/data/db/
    ports:
      - "27017:27017"
  translator:
    image: "translator"
    build: ./translator
    container_name: "translator"
    depends_on:
      - flask
